language: python

python:
    - "2.7"
    - "3.4"

install:
    - pip install flask --use-mirrors
    - pip install flask-testing --use-mirrors
    - pip install coveralls --use-mirrors

script: python setup.py test
